### ISSUE TITLE
No Score Rank

### ISSUE THREAD

**Issue by QuinTekno** [respektive/osu-tracker#13]
I started using the tracker yesterday but it says "no score rank". 
Is this a bug or something I messed up?
![image_2023-12-10_194904395](https://github.com/respektive/osu-tracker/assets/142257148/ce22b579-4c85-4b52-b733-8c8bc950ada4)

**Comment by respektive** [comment]
Unfortunately the tracker is only able to show your score rank if you have enough ranked score to be in the top 10,000. The reason being that the osu! api only has an endpoint to get the score ranking (https://osu.ppy.sh/docs/#get-ranking), which only goes up to rank 10,000. 

There is an open issue on the osu-web repo to add this rank back to the user profiles (https://github.com/ppy/osu-web/issues/5620), but until then this is the only way to retrieve it.
